version: '3.8'
services:
  webclient:
    container_name: webclient
    build: ./webclient
    environment:
      NODE_ENV: production
    ports:
        - 80:80
    volumes:
      - ./usr/local/app/dist/growing-solution:/usr/share/nginx/html
