name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          mkdir projects
          cd projects
          git clone https://github.com/GrowingDev/growing-solution.git
          cd growing-solution/webclient
          docker build -t growingdev/growing-solution-webclient-image:latest  .
          docker image ls
          docker run -d -p 8080:80 growingdev/growing-solution-webclient-image:latest 

# go to directory where you want to pull the repository 