name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd projects
          git clone https://github.com/GrowingDev/growing-solution.git
          cd growing-solution/webclient
          docker compose stop
          docker compose build --no-cache
          docker compose up -d --force-recreate